ENCODER_MAP_ENABLE = no
AUTO_SHIFT_ENABLE = yes
TAP_DANCE_ENABLE = yes
LEADER_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
MODTAP_ENABLE = yes

UNICODE_COMMON = yes
UNICODE_ENABLE = yes
UNICODEMAP_ENABLE = no